[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32-p4
framework = arduino
monitor_speed = 460800
upload_speed = 921600

; --- 32MB FLASH BOUNDARY SETTINGS ---
board_upload.flash_size = 32MB
board_upload.maximum_size = 33554432
board_upload.maximum_ram_size = 33554432
board_build.partitions = ./custom_32MB.csv
board_build.cpu_frequency = 400MHz

; --- COMPILER FLAGS FOR STANDARD TARGETS & 32MB PSRAM ---
build_flags =
    -march=rv32imafc_zicsr_zifencei
    -D BOARD_HAS_PSRAM

build_unflags =
    -march=rv32imafc_zicsr_zifencei_xesppie
    -march=rv32imafc_zicsr_zifencei_xesploop_xespv

lib_ldf_mode = deep
lib_deps =
    FS
    SD_MMC
    ESPmDNS
    ArduinoJson
    WiFi
    WebServer

extra_scripts = pre:prep.py